# Generated by Django 2.2.7 on 2019-11-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
